name: Update NSG Rules

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *" # Ejecuta cada hora para actualizar la IP
  workflow_dispatch:
    inputs:
      user_ip:
        description: 'IP pública desde donde permitir acceso'
        required: true

jobs:
  update-nsg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # - name: Get user public IP
      #   run: bash scripts/update_nsg.sh
      # Comentado porque ya no se usa, la IP viene como input manual

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_user_ip: ${{ github.event.inputs.user_ip }}
        run: terraform apply -auto-approve
        working-directory: terraform
